version: "3.7"

services:
  campshot-db:
    image: mdillon/postgis:11-alpine
    environment:
      - POSTGRES_DB=${DB_NAME:-csdb1}
      - POSTGRES_USER=${DB_USER:-csuser}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-cspass}
    volumes:
      - ${DB_LOCAL_DATA:-./dbdata}:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5


  campshot-server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./app_init_local.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - campshot-db